name: 'Assign reviewer by label'
description: 'assign and remove reviewer when specified labels applied'
branding:
  icon: 'users'  
  color: 'yellow'
inputs:
  token:
    description: 'github token or personal access token'
    required: true
  labels:
    description: 'labels as trigger (JSON array)'
    required: true
  reviewers:
    description: 'reviewers (JSON array)'
    required: true
  remove-when-no-label:
    description: 'remove reviewers if specified labels not applied'
    required: false
    default: 'false'
outputs:
  type:
    description: 'assign or remove'
  skipped:
    description: 'true or false'
  url:
    description: 'Pull repuest URL'
runs:
  using: 'node16'
  main: 'dist/index.js'
