name: 'Assign reviewer by label'
description: 'assign and remove reviewer when specified labels applied'
branding:
  icon: 'users'  
  color: 'yellow'
inputs:
  token:
    description: 'github token or personal access token'
    required: true
    default: ''
  labels:
    description: 'labels as trigger (JSON array)'
    required: true
    default: ''
  reviewers:
    description: 'reviewers (JSON array)'
    required: true
    default: ''
outputs:
  type:
    description: 'assign or remove'
  skipped:
    description: 'true or false'
  url:
    description: 'Pull repuest URL'
runs:
  using: 'node12'
  main: 'dist/index.js'
